# Sample Logstash configuration for creating a simple
# Beats -> Logstash -> Elasticsearch pipeline.

input {
  file {
    type => "log"
    path => "E:/Abdul/Microservices/logs/*.log" 
    start_position => beginning	
  }
}

filter {

 grok {
    match => [ "message",
               "%{TIMESTAMP_ISO8601:timestamp1}  %{WORD:loglevel} \[%{GREEDYDATA:appname},%{GREEDYDATA:traceId},%{GREEDYDATA:spanid}\] %{NUMBER:processID} %{GREEDYDATA:out}"               
             ]
  }


  date {
    match => [ "timestamp" , "yyyy-MM-dd HH:mm:ss.SSS" ]
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
	cacert => 'config/cert/http_ca.crt'
	user => logstash_internal
    password => abdul1234
	index =>"ecommerce"
  }
  
}