
server.port=8888
spring.application.name=AbdulConfigServer
spring.cloud.config.server.git.uri = file://E:/Abdul/Microservices/config-files
#spring.cloud.config.server.native.searchLocations=file://E:/Abdul/Microservices/config-files
eureka.client.serviceUrl.defaultZone=http://localhost:5656/eureka/
#spring.profiles.active=native

management.dynatrace.metrics.export.uri=https://lmo77507.live.dynatrace.com/api/v2/metrics/ingest
management.dynatrace.metrics.export.api-token=dt0c01.ICDHA44ARLBDD6P2A6RKFUEG.2GGNUCREAQH7W33DQXYRRQEFFOWM47WR2RGXIM2DRJJPJOBRQHMKV7PRYZPEC6KU
