#server.port=5656
#spring.application.name=eureka
#eureka.client.serviceUrl.defaultZone=http://localhost:5656/eureka/


management.endpoints.web.exposure.include=*
endpoints.env.keys-to-sanitize=password,secret
management.endpoint.env.show-values=ALWAYS

management.dynatrace.metrics.export.uri=https://lmo77507.live.dynatrace.com/api/v2/metrics/ingest
management.dynatrace.metrics.export.api-token=dt0c01.ICDHA44ARLBDD6P2A6RKFUEG.2GGNUCREAQH7W33DQXYRRQEFFOWM47WR2RGXIM2DRJJPJOBRQHMKV7PRYZPEC6KU
management.dynatrace.metrics.export.v2.metric-key-prefix=spring-boot-eureca
management.dynatrace.metrics.export.v2.enrich-with-dynatrace-metadata=true
management.dynatrace.metrics.export.enabled=false

management.tracing.sampling.probability=1.0
management.tracing.enabled=false

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]