#server.port=5656
#spring.application.name=eureka
#eureka.client.serviceUrl.defaultZone=http://localhost:5656/eureka/


management.endpoints.web.exposure.include=*
endpoints.env.keys-to-sanitize=password,secret
management.endpoint.env.show-values=ALWAYS
