spring.application.name=dbservice
server.port=0
source=dbservice.dev.properties
spring.cloud.function.definition=getOrder;getNewOrder
#spring.cloud.stream.bindings.getOrder-in-0.destination=dbconsumer
spring.cloud.stream.bindings.getOrder-in-0.destination=orderQueue
spring.cloud.stream.bindings.getNewOrder-in-0.destination=orderQueue
nameAutorefreshed=New property 

management.endpoints.web.exposure.include=*
eureka.instance.metadata-map.metrics.path=/actuator/prometheus
eureka.instance.metadata-map.health.path=/actuator/health
eureka.instance.metadata-map.management.context-path=/actuator

management.dynatrace.metrics.export.uri=https://lmo77507.live.dynatrace.com/api/v2/metrics/ingest
management.dynatrace.metrics.export.api-token=dt0c01.ICDHA44ARLBDD6P2A6RKFUEG.2GGNUCREAQH7W33DQXYRRQEFFOWM47WR2RGXIM2DRJJPJOBRQHMKV7PRYZPEC6KU

management.dynatrace.metrics.export.v2.metric-key-prefix=spring-boot-dbservice
management.dynatrace.metrics.export.v2.enrich-with-dynatrace-metadata=true
management.dynatrace.metrics.export.enabled=false

management.tracing.sampling.probability=1.0
management.tracing.enabled=true

spring.h2.console.enabled=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor


logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]