spring.application.name=ecommerce
server.port=0
source=ecommerce.dev.properties1
eCommercePortalName=AbdulEcommerce1
#spring.cloud.stream.bindings.supplyOrder-out-0.destination=my-topic
spring.cloud.stream.bindings.supplyOrder-out.destination=orderQueue
#spring.cloud.stream.function.definition=supplyOrder
#spring.cloud.stream.rabbit.bindings.myChannel.producer.bindQueue=true
#spring.cloud.stream.rabbit.bindings.myChannel.producer.exchangeAutoDelete=false
#spring.cloud.stream.rabbit.bindings.myChannel.producer.exchangeType=fanout
#spring.cloud.stream.rabbit.bindings.myChannel.producer.queueBindingArguments.x-match=any

management.endpoints.web.exposure.include=*
eureka.instance.metadata-map.metrics.path=/actuator/prometheus
eureka.instance.metadata-map.health.path=/actuator/health
eureka.instance.metadata-map.management.context-path=/actuator

management.dynatrace.metrics.export.uri=https://lmo77507.live.dynatrace.com/api/v2/metrics/ingest
management.dynatrace.metrics.export.api-token=dt0c01.ICDHA44ARLBDD6P2A6RKFUEG.2GGNUCREAQH7W33DQXYRRQEFFOWM47WR2RGXIM2DRJJPJOBRQHMKV7PRYZPEC6KU

management.dynatrace.metrics.export.v2.metric-key-prefix=spring-boot-eCommerce
management.dynatrace.metrics.export.v2.enrich-with-dynatrace-metadata=true
management.dynatrace.metrics.export.enabled=false

management.tracing.sampling.probability=1.0